---
# when: desired_state == 'absent'
- name: Remove directories
  when: delete_caches is defined
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ kubeblocks_repo }}"
    - "{{ kubeblocks_cache }}"

- name: Remove KubeBlocks addons
  when: use_kubeblocks | bool
  ansible.builtin.include_tasks: addons.yml
  loop: "{{ kubeblocks_add_ons }}"
  loop_control:
    label: "addon: {{ item }}"

- name: Remove KubeBlocks
  ansible.builtin.command: >
    kbcli --kubeconfig={{ k8s_auth_kubeconfig }} kubeblocks uninstall -n kb-system
        --auto-approve=true
  changed_when: true

- name: Remove KubeBlocks crds
  ansible.builtin.shell: |
    set -o pipefail;
    kubectl --kubeconfig={{ k8s_auth_kubeconfig }} get crd -o name \
    | grep kubeblocks.io \
    | xargs kubectl --kubeconfig={{ k8s_auth_kubeconfig }} delete
  changed_when: true
  failed_when: false  # for example rc 123 is empty list as inputs

- name: Remove kb-system
  kubernetes.core.k8s:
    name: kb-system
    api_version: v1
    kind: Namespace
    state: absent
    wait: true
