---

- name: "Pull addon {{ item.addon_name }}"
  kubernetes.core.helm_pull:
    chart_ref: "{{ helm_repo_url }}/{{ item.addon_name }}"
    chart_version: "{{ item.version }}"
    username: "{{ registry_user }}"
    password: "{{ registry_pass }}"
    untar_chart: false
    destination: "{{ kubeblocks_repo }}"
  when:
    - desired_state == "present"
    - item.state == "present"
    - "'-cluster' not in item.addon_name"

- name: "Manage addon {{ item.addon_name }}"
  kubernetes.core.helm:
    binary_path: "{{ helm_binary }}"
    name: "kb-addon-{{ item.addon_name }}"
    chart_ref: "{{ kubeblocks_repo }}/{{ item.addon_name }}-{{ item.version }}.tgz"
    release_namespace: kb-system
    create_namespace: true
    values:
      image.registry: "{{ registry_host }}"
    reuse_values: true
    state: "{{ desired_state }}"
    wait: false
  when:
    - desired_state == "present"
    - item.state == "present"
    - "'-cluster' not in item.addon_name"
    - item.addon_name != "kubeblocks"
