---
- name: "When not enabled run kbcli uninstall addon {{ item.addon_name }}"
  when: (desired_state == "absent" or item.state == "absent") and ("'-cluster' not in item.addon_name")
  ansible.builtin.command: "kbcli --kubeconfig={{ k8s_auth_kubeconfig }} addon uninstall --auto-approve=false {{ item.addon_name }}"
  register: item_state
  failed_when: false
  ignore_errors: true
  changed_when: false

- name: "Ensure add-on absent by Helm: {{ item.addon_name }}"
  when: (desired_state == "absent" or item.state == "absent") and ("'-cluster' not in item.addon_name")
  kubernetes.core.helm:
    binary_path: "{{ helm_binary }}"
    name: "kb-addon-{{ item.addon_name }}"
    release_namespace: kb-system
    state: absent
    wait: true
  failed_when: false

- name: "Pull addon {{ item.addon_name }}"
  kubernetes.core.helm_pull:
    chart_ref: "{{ helm_repo_url }}/{{ item.addon_name }}"
    chart_version: "{{ item.version }}"
    username: "{{ registry_user }}"
    password: "{{ registry_pass }}"
    untar_chart: false
    destination: "{{ kubeblocks_repo }}/"
  when:
    - desired_state == "present"
    - item.state == "present"
    - "'-cluster' not in item.addon_name"

# snapshot-controller chart needs to be patched with the private image url
- name: "Manage addon {{ item.addon_name }}"
  kubernetes.core.helm:
    binary_path: "{{ helm_binary }}"
    name: "kb-addon-{{ item.addon_name }}"
    chart_ref: "{{ kubeblocks_repo }}/{{ item.addon_name }}-{{ item.version }}.tgz"
    release_namespace: kb-system
    create_namespace: true
    values:
      image.repository: "{{ registry_host }}/sig-storage/snapshot-controller"
    reuse_values: true
    state: "present"
    wait: true
  when:
    - registry_host is defined
    - desired_state == "present"
    - item.state == "present"
    - "'-cluster' not in item.addon_name"
    - item.addon_name == "snapshot-controller"

# The charts can to be patched with the private registry_host
- name: "Manage addon {{ item.addon_name }}"
  kubernetes.core.helm:
    binary_path: "{{ helm_binary }}"
    name: "kb-addon-{{ item.addon_name }}"
    chart_ref: "{{ kubeblocks_repo }}/{{ item.addon_name }}-{{ item.version }}.tgz"
    release_namespace: kb-system
    create_namespace: true
    values:
      image.registry: "{{ registry_host is defined | ternary(registry_host, omit) }}"
    reuse_values: true
    state: "present"
    wait: true
  when:
    - desired_state == "present"
    - item.state == "present"
    - "'-cluster' not in item.addon_name"
    - item.addon_name != "kubeblocks"
