- name: "Ensure add-on {{ item.addon_name }} is {{ item.state }}."
  kubernetes.core.helm:
    name: "kb-addon-{{ item.addon_name }}"
    chart_ref: "{{ helm_repo_name }}/{{ item.addon_name }}"
    chart_version: "{{ item.version }}"
    release_namespace: 'kb-system'
    state: "{{ item.state }}"

- name: "Ensure add-on {{ item.addon_name }} is {{ 'enabled' if item.enabled else 'disabled' }}."
  when: item.state == 'present'
  ansible.builtin.command: "kbcli --kubeconfig={{ k8s_auth_kubeconfig }} addon {{ 'enable' if item.enabled else 'disable' }} {{ item.addon_name }}"
  changed_when: true
