- name: "Ensure add-on {{ item.addon_name }} is {{ item.state }}."
  kubernetes.core.helm:
    name: "{{ item.addon_name }}"
    chart_ref: "{{ helm_repo_name }}/{{ item.addon_name }}"
    chart_version: "{{ item.version }}"
    release_namespace: "{{ item.addon_namespace }}"
    create_namespace: true
    state: "{{ item.state }}"
