- name: "When not enabled run kbcli uninstall addon {{ item.addon_name }}"
  when: not (item.enabled | bool)
  ansible.builtin.command: "kbcli --kubeconfig={{ k8s_auth_kubeconfig }} addon uninstall --auto-approve=false {{ item.addon_name }}"
  register: item_state
  failed_when: false
  ignore_errors: true
  changed_when: false

- name: "Ensure add-on state absent: {{ item.addon_name }}"
  kubernetes.core.helm:
    binary_path: "{{ helm_binary }}"
    name: "kb-addon-{{ item.addon_name }}"
    release_namespace: kb-system
    state: absent
    wait: false
  when:
    - item.state == "absent"
    - "'-cluster' not in item.addon_name"
