---
# Install KubeBlocks with Helm chart
# ~/.kube/config should be valid

- name: Gather information of kubeblocks chart in kb-system namespace
  kubernetes.core.helm_info:
    binary_path: "{{ helm_binary }}"
    name: kubeblocks
    release_namespace: kb-system
  register: kubeblocks_info

- name: Display kubeblocks_info
  ansible.builtin.debug:
    msg: "{{ kubeblocks_info }}"

# TODO some states are not covered yet
- name: Manage the KubeBlocks chart
  when: kubeblocks_info.status is not defined or ( kubeblocks_info.status.status != "pending" or kubeblocks_info.status.status != "deployed")
  ansible.builtin.command: >
    helm --kubeconfig {{ k8s_auth_kubeconfig }} install kubeblocks oci://{{ registry_host }}/helm-apecloud/kubeblocks
    --version 0.9.2
    --namespace kb-system
    --create-namespace
    --set image.registry={{ registry_host }}
    --set dataProtection.image.registry={{ registry_host }}
    --set addonChartsImage.registry={{ registry_host }}
  changed_when: true
