---
# Create Snapshot controller
# Create custom resource definitions from kubeblocks_crds.yaml
# ~/.kube/config should be valid

- name: Copy the yaml files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ kubeblocks_cache }}/"
    mode: '0664'
  loop:
    - "{{ crd_manifest }}"
    - snapshot.storage.k8s.io_volumesnapshotclasses.yaml
    - snapshot.storage.k8s.io_volumesnapshotcontents.yaml
    - snapshot.storage.k8s.io_volumesnapshots.yaml

- name: Create Snapshot Contoller
  kubernetes.core.k8s:
    state: present
    src: "{{ kubeblocks_cache }}/{{ item }}"
    validate:
      fail_on_error: true
    wait: true
  loop:
    - snapshot.storage.k8s.io_volumesnapshotclasses.yaml
    - snapshot.storage.k8s.io_volumesnapshotcontents.yaml
    - snapshot.storage.k8s.io_volumesnapshots.yaml

- name: Create dependent CRDs
  kubernetes.core.k8s:
    state: present
    src: "{{ kubeblocks_cache }}/{{ crd_manifest }}"
    namespace: kube-system
    validate:
      fail_on_error: true
    wait: true
